name: 'check validates_timeliness new version'
description: 'For the devs who installed a different branch to support Rails 7 and still want to know if an official version is available.'
author: '@ariccio'
branding:
  icon: code
  color: red
outputs:
  maybe-new-version:
    description: non-null if the latest reported version has changed
    value: $${{ steps.run.outputs }}
runs:
  using: 'composite'
  steps:
    - run: |
        bundle exec ruby run.rb
      shell: bash