name: 'check validates_timeliness new version'
description: 'For the devs who installed a different branch to support Rails 7 and still want to know if an official version is available.'
author: '@ariccio'
branding:
  icon: code
  color: red
outputs:
  maybe-new-version:
    description: non-null if the latest reported version has changed
    value: $${{ steps.run.outputs.maybe-new-version }}
runs:
  using: 'composite'
  steps:
    - run: |
        echo '::echo::on'
        result=$(bundle exec ruby run.rb)
        echo "::set-output name=maybe-new-version::$result"
        echo "${{toJSON(steps)}}"
      shell: bash